config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #  GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end

  end

  resources :badges, only: %i[index]

  resources :badges_users, only: %i[index]

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum file_name: [:badge_category, :badge_first_try, :badge_level]
  enum rule: [:by_category, :first_try, :by_level]
  enum rule_parameter: [:solar_system, :animals, :constellations, :light_level, :medium_level, :high_level, :not]

  belongs_to :author_badge, class_name: 'Admin', foreign_key: 'author_badge_id'

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :name, presence: true
  validates :file_name, presence: true
  validates :rule, presence: true
  validates :rule_parameter, presence: true

  def self.only_level_difficult
    by_level.pluck(:rule_parameter)
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = current_user.created_badges.build(badge_params)
    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :file_name, :rule, :rule_parameter)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align_middle"><%= badge.name %></td>
  <td class="align_middle"><%= badge.file_name + "." + "jpg" %></td>
  <td class="align_middle"><%= badge.author_badge.email %></td>
  <td class="align_middle"><%= badge.rule %></td>
  <td class="align_middle"><%= badge.rule_parameter %></td>
  <td class="align_middle"><%= link_to 'Просмотр бейджа', admin_badge_path(badge) %></td>
  <td class="align_middle">
    <%= link_to 'Редактировать бейдж',
                edit_admin_badge_path(badge)%>
  </td>
  <td class="align_middle"><%= link_to 'Удалить бейдж', admin_badge_path(badge), method: :delete, data: { confirm: "Вы уверены?"} %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: :name %>
  </p><br>

  <p>
    <%= form.label :file_name %>
    <%= form.select :file_name, Badge.file_names.keys.to_a %>
  </p><br>

  <p>
    <%= form.label :rule %>
    <%= form.select :rule, Badge.rules.keys.to_a  %>
  </p><br>

  <p>
    <%= form.label :rule_parameter %>
    <%= form.select :rule_parameter, Badge.rule_parameters.keys.to_a %>
  </p><br>

  <p><%= form.submit%>

<% end %>

app/views/admin/badges/edit.html.erb
<h1>Редактировать бейдж <%= @badge.name %></h1>

<%= render 'form' %>
<%= link_to 'Назад', admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1>Все бейджи</h1>

<p><%= link_to 'Новый badge', new_admin_badge_path %></p>

<%= render 'shared/errors', resource: @badge %>
<table class="table">
  <tr>
    <th>Name</th>
    <th>File_name</th>
    <th>Author</th>
    <th>Rules</th>
    <th>Rule_parameter</th>
    <th colspan="5">Действия</th>
  </tr>
  <%= render @badges %>
</table>
<%= link_to 'Назад', admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1>Создать новый бейдж</h1>

<%= render 'form' %>
<%= link_to 'Назад', admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>File_name:</strong>
  <%= @badge.file_name %>
  <%= image_tag "#{@badge.file_name + "." + "jpg"}", :class => "style_image_badge" %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @badge.rule %>
</p>

<p>
  <strong>Rule_parameter:</strong>
  <%= @badge.rule_parameter %>
</p>

<p>
  <strong>Author:</strong>
  <%= @badge.author_badge.email %>
</p><br>

<%= link_to 'Редактировать', edit_admin_badge_path(@badge) %> |
<%= link_to 'Назад', admin_badges_path %>