config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #  GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end

  end

  resources :badges, only: %i[index]

  resources :badges_users, only: %i[index]

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true, foreign_key: 'question_id'

  before_validation :set_current_question

  SUCCESS_RATIO = 85

  def accept!(answer_ids)
    return if time_over?

    self.correct_questions +=1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil? || time_over?
  end

  def successful?
    percent >= SUCCESS_RATIO
  end

  def percent
    ((correct_questions.to_f / total_question_number.to_f ) * 100).to_i
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def total_question_number
    test.questions.count
  end

  def timer_left_time
    timer_finish_time - Time.now
  end

  def timer_finish_time
    created_at.to_time + test.timer * 60
  end

  def time_over?
    timer_left_time <= 0
  end

  private

  def set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question
      test.questions.order(:id).where('id > ?', current_question.id).first
    else
      test.questions.first if test.present?
    end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show result update]

  def show; end

  def result
    @badges = Badge.find(params[:badges_ids]) if params[:badges_ids]
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      @user_badges = BadgeAdditionService.new(@test_passage, current_user).call
      add_badges_user(@user_badges, current_user)
      redirect_to result_test_passage_path(@test_passage, badges_ids: badges_ids_user(@user_badges))
    else
      render :show
    end
  end

  def set_badge(number)
    @badge = Badge.find(number)
  end

  def add_badges_user(badges, user)
    badges.each { |badge| user.badges.push(badge) }
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def badges_ids_user(user_badges)
    user_badges.map {|badge| badge.id} if user_badges.any?
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1>Тест <%=@test_passage.test.title %> был завершен!</h1>

  <h2>Количество правильных ответов: <%= @test_passage.correct_questions %>
    из <%= @test_passage.total_question_number %><br>
  </h2>


<h3> Процент успеха:
<% if @test_passage.successful? %>
    <p style="color:#32CD32"><%= "#{@test_passage.percent}%"%><br></p> Тест пройден
<% else %>
    <p style="color:#DC143C"><%= "#{@test_passage.percent}%"%><br></p> Тест не пройден
<% end %>
</h3>

<% if @badges %>
  <% @badges.each do |badge| %>
    <p>Вы получили бейдж:</p>
    <%=badge.name %>
    <%= image_tag "#{badge.file_name + "." + "jpg"}", :class => "style_image_badge" %><br>
  <% end %>
<% end %>
<br>
<%= link_to 'Назад к списку всех тестов', tests_path %>

app/views/test_passages/show.html.erb
<h1>Текущий тест: <%= @test_passage.test.title %></h1>

<h3>Вопрос: <%= @test_passage.current_question_number %> из <%=@test_passage.total_question_number %></h3>

<b>
  <b><%= @test_passage.current_question.body %></b>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden:
      false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p><%= link_to 'Gist Question', test_passage_gists_path(@test_passage), method: :post %></p>

  <div class="progress-status">
    <%= content_tag :div, '', class: 'myprogress-bar', data: { progress_info: @test_passage.current_question_number * 100 / @test_passage.total_question_number } do %>
    <% end %>
  </div><br>

  <%= content_tag :div, '', id: 'minutes', data: { left_time: @test_passage.timer_left_time } do %>
  <% end %>
  <div id="timer"></div>


 <p><%= form.submit 'Next'%></p>
<% end %>