config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #  GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end

  end

  resources :badges, only: %i[index]

  resources :badges_users, only: %i[index]

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :count_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def count_answers
    errors.add(:answers) if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: "Answer was successfully created."
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), notice: "Answer was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct, :question_id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Просмотр', admin_answer_path(answer) %> |
  <%= link_to 'Редактировать', edit_admin_answer_path(answer) %> |
  <%= link_to 'Удалить', admin_answer_path(answer),
              method: :delete,
              data: { confirm: "Вы уверены?"} %><br><br>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer  %>

  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, size: "100x10" %>
  </p><br>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p><br>

  <p>
    <%= form.label :question_id %>:
    <%= form.collection_select :question_id, Question.all, :id, :body, prompt: true %>
  </p><br>

  <p><%= form.submit%>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Редактировать ответ</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@answer.question)%>

app/views/admin/answers/new.html.erb
<h1>Новый ответ</h1>
<p>
  <%= @question.body %>
</p>

<%= render 'form', answer: @answer %>
<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', admin_question_path(@answer.question) %>