config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  #  GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end

  end

  resources :badges, only: %i[index]

  resources :badges_users, only: %i[index]

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = Question.new(test: @test)
  end

  def edit; end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_tests_path(@question.test)
  end

  private

  def question_params
    params.require(:question).permit(:body, :test_id)
  end

  def find_question
    @question = Question.find(params[:id])
  end


  def find_test
    @test = Test.find(params[:test_id])
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      operation = "Edit"
    else
      operation = "Create New"
    end
    "#{operation} #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :question_body %>
  </p><br>

  <p>
    <%= form.label :test_id %>:
    <%= form.collection_select :test_id, Test.all, :id, :title, prompt: true %>
  </p><br>

  <p><%= form.submit%>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td><br>
  <%= link_to 'Просмотр', admin_question_path(question) %> |
  <td><%= link_to 'Редактировать', edit_admin_question_path(question) %></td> |
  <td><%= link_to 'Удалить', admin_question_path(question),
                  method: :delete,
                  data: { confirm: "Вы уверены?"} %></td><br><br>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question)%></h1>

<%= render 'form' %>
<%= link_to 'Назад', admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question)%></h1>

<%= render 'form'%>

<%= link_to 'Назад', admin_tests_path %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title%> Question</h1>
<p>
  <%= @question.body %>
</p>

<h2>Answers</h2>
  <%= link_to 'Новый ответ', new_admin_question_answer_path(@question) %><br><br>
<al>
  <%= render @question.answers %>
</al>

<%= link_to 'Edit', edit_admin_question_path(@question) %> |
<%= link_to 'Back', admin_test_path(@question.test) %><br><br>